name: Optimize images
on:
  workflow_dispatch:
  push:

permissions:
  contents: write

jobs:
  optimize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Optimize images to WebP
        uses: valentin-kaiser/webppipe@master
        with:
          quality: "82"
          max-width: "1920"
          commit: "true"
          push: "true"
          commit-message: "[GEN] optimize images to WebP"
